### ISSUE TITLE
meteor 1.2

### ISSUE THREAD

**Issue by tcastelli** [ElevateDev/meteor-autoform-jquery-payments#2]
Since this package uses https://github.com/aldeed/meteor-template-extension
I see that for meteor 1.2, version 4.x.x should be used instead. 
Any chance of updating the dependency in package.json?

**Comment by jimmiebtlr** [comment]
Could I get you to check if 0.0.7-rc.1 fixes this for you?  You'll need to specify that version specifically to get it to upgrade.

meteor add elevatedevdesign:autoform-jquery-payments@0.0.7-rc.1

**Comment by tcastelli** [comment]
thanks, yes that fixes the dependency problem

**Comment by jimmiebtlr** [comment]
Published in 0.0.8.
